### ISSUE TITLE
Questions about commands

### ISSUE THREAD

**Issue by NielsPilgaard** [MommyHeather/AdvancedBackups#28]
I'm wondering, what do the following commands do?

- check
- force-backup
    - How is this different from start?

Another note, perhaps it would be best to rename the reload config command to reload-config or similar. Reload is a bit vague to me.

Additionally, I recommend using `/backup` instead of `/advancedbackups`, since `/backup` is the norm. Or add an alias, if that's.. a thing.

**Comment by MommyHeather** [comment]
- `check` runs the checks made before a backup (time since last backup, player activity etc) and tells you if one would be made with `start`
- `force-backup` is the same as `start` *but* it bypasses any checks.

These are [documented](https://github.com/MommyHeather/AdvancedBackups#commands) - do you think this needs clarifying (or some other adjustments?)


And yeah, I guess I'll rename the command - I had it named the way it was as I didn't want to risk conflict with other mods, in the event that someone has both advancedbackups and another backup mod installed.

**Comment by MommyHeather** [comment]
Perhaps `check` and `force-backup` should be removed, and `start` should just ignore the checks...?

**Comment by NielsPilgaard** [comment]
You can add a Wiki link so it actually displays "Wiki" at the top, along description, source etc

**Comment by MommyHeather** [comment]
Good point. I'll do that too.

**Comment by MommyHeather** [comment]
So, this is now all done - can you think of anything else needed, or should I release v2.2?

**Comment by NielsPilgaard** [comment]
I think we're good to go 👍

**Comment by MommyHeather** [comment]
Awesome! I'll get it on curseforge/modrinth when built then - CF may take some time to approve, MR has been pretty quick in my experience
