### ISSUE TITLE
Version request : Forge 1.20.2

### ISSUE THREAD

**Issue by NorthLake** [MommyHeather/AdvancedBackups#32]
**New Minecraft version :** 1.20.2
**New modloader :** Forge

1.20.2 has been out for a little while now, Any progress on it? 🙂

**Comment by MommyHeather** [comment]
Hey!
[AdvancedBackups-forge-1.20-2.4.zip](https://github.com/MommyHeather/AdvancedBackups/files/12898358/AdvancedBackups-forge-1.20-2.4.zip)

That's my bad, I never did get around to marking 1.20.2 as supported on forge because of the Neoforge situation. This file works, it's also on modrinth but is awaiting approval on curseforge. I'll mark it as supported on both of those platforms.

**Comment by MommyHeather** [comment]
Of course, feel free to re-open if there's any issues! I'd suggest using the file on modrinth / here over the most recent forge 1.20 CF file, as the 2.4 version fixes a fairly major bug.
