### ISSUE TITLE
Feature request : Explain what the differential and incremental backup types are.

### ISSUE THREAD

**Issue by hattrickpatrick** [MommyHeather/AdvancedBackups#46]
**Is your feature request related to a problem? Please describe.**
Your AdvancedBackups mod mentions three types of backups, zip, differential, and incremental. ZIP is fairly self-explanatory but the differential and incremental backup types aren't explained/described.

**Describe the solution you'd like**
I've used other backup mods in the past that describe one or the other and at times they seem to be used interchangeably by developers, so an explanation of how your mod uses/defines them would be very helpful, especially for people who might not be familiar with the terms at all.

**Comment by MommyHeather** [comment]
I'll get them documented, my bad.

- Zip backups are fairly self explanatory - zip up the whole world and there's your backup.
- Differential backups have a concept of "full" and "partial" backups :
    - "full" backups are the same as a zip. 
    - "partial" backups contain only the files that have changed since the last "full" backup. This can greatly reduce space usage.
    
- Incremental backups are similar to differential, but they backup files that have changed since the last *partial* instead - which further reduces space usage, but can create an instability as a loss of a partial can damage all backups up until the next full backup. They also take the longest to restore.
